site_name: cypress' blog
site_author: cypress
theme:
  name: material
  features:
    - navigation.indexes
  palette:
    # 亮色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至暗色模式

    # 暗色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式

markdown_extensions:
  - toc:
      permalink: true        # 添加段落链接
      toc_depth: 3          # 目录深度
      separator: "_"        # 标题锚点分隔符
      title: "目录"         # 目录标题

plugins:
  - blog:
      blog_dir: blog
      post_url_format: "{slug}"
      post_excerpt: optional


nav:
  - blog:
      - blog/index.md
      - 笔记:
          - ssm:
              - spring: note/ssm/spring.md
              - springmvc: note/ssm/springmvc.md
              - mybatis: note/ssm/mybatis.md
          - 数据结构:
              - 代码随想录:
                  - 数组:
                      - 二分查找: note/datastructure/array/binary-search.md
                      - 快慢指针: note/datastructure/array/fast-slow-pointer.md
                      - 双指针: note/datastructure/array/double-pointer.md
                      - 滑动窗口: note/datastructure/array/sliding-window.md
                      - 螺旋矩阵: note/datastructure/array/spiral-matrix.md
                      - 区间和: note/datastructure/array/interval-sum.md
                      - 分配土地: note/datastructure/array/land-allocation.md
          - 计组:
            - csapp: note/cs_composition/csapp.md
            - cs61c:
                - knowledge:
                  - 内存管理: note/cs_composition/cs61c/knowledge/memory_management.md
                  - 浮点数: note/cs_composition/cs61c/knowledge/floating-point.md
                  - risv-v: note/cs_composition/cs61c/knowledge/risv-v.md
                - labs:
                  - lab1: note/cs_composition/cs61c/labs/lab1.md
                  - lab2: note/cs_composition/cs61c/labs/lab2.md
                - projects:
                  - project1: note/cs_composition/cs61c/projects/project1.md
          - 计网: note/cs-net.md
          - 操作系统: note/os.md
          - 图灵完备: note/turing.md
          - 建站教程: note/site-construction.md
      - summary:
          - 2025年:
              - 1月:
                  - summary/25year/1month/index.md
                  - 第一周: summary/25year/1month/1week.md
                  - 第二周: summary/25year/1month/2week.md
                  - 第三周: summary/25year/1month/3week.md
                  - 第四周: summary/25year/1month/4week.md
              - 2月:
                  - summary/25year/2month/index.md
                  - 第一周: summary/25year/2month/1week.md
                  - 第二周: summary/25year/2month/2week.md
                  - 第三周: summary/25year/2month/3week.md
                  - 第四周: summary/25year/2month/4week.md
              - 3月:
                  - 第一周: summary/25year/3month/1week.md
                  - 第二周: summary/25year/3month/2week.md
                  - 第三周: summary/25year/3month/3week.md
                  - 第四周: summary/25year/3month/4week.md
              - 4月:
                  - 第一周: summary/25year/4month/1week.md
                  - 第二周: summary/25year/4month/2week.md
                  - 第三周: summary/25year/4month/3week.md
                  - 第四周: summary/25year/4month/4week.md
              - 5月:
                  - 第一周: summary/25year/5month/1week.md
                  - 第二周: summary/25year/5month/2week.md
                  - 第三周: summary/25year/5month/3week.md
                  - 第四周: summary/25year/5month/4week.md
              - 6月:
                  - 第一周: summary/25year/6month/1week.md
                  - 第二周: summary/25year/6month/2week.md
                  - 第三周: summary/25year/6month/3week.md
                  - 第四周: summary/25year/6month/4week.md
              - 7月:
                  - 第一周: summary/25year/7month/1week.md
                  - 第二周: summary/25year/7month/2week.md
                  - 第三周: summary/25year/7month/3week.md
                  - 第四周: summary/25year/7month/4week.md
              - 8月:
                  - 第一周: summary/25year/8month/1week.md
                  - 第二周: summary/25year/8month/2week.md
                  - 第三周: summary/25year/8month/3week.md
                  - 第四周: summary/25year/8month/4week.md
              - 9月:
                  - 第一周: summary/25year/9month/1week.md
                  - 第二周: summary/25year/9month/2week.md
                  - 第三周: summary/25year/9month/3week.md
                  - 第四周: summary/25year/9month/4week.md
              - 10月:
                  - 第一周: summary/25year/10month/1week.md
                  - 第二周: summary/25year/10month/2week.md
                  - 第三周: summary/25year/10month/3week.md
                  - 第四周: summary/25year/10month/4week.md
              - 11月:
                  - 第一周: summary/25year/11month/1week.md
                  - 第二周: summary/25year/11month/2week.md
                  - 第三周: summary/25year/11month/3week.md
                  - 第四周: summary/25year/11month/4week.md
              - 12月:
                  - 第一周: summary/25year/12month/1week.md
                  - 第二周: summary/25year/12month/2week.md
                  - 第三周: summary/25year/12month/3week.md
                  - 第四周: summary/25year/12month/4week.md

