site_name: cypress' blog
site_author: cypress
theme:
  name: material
  features:
    - navigation.indexes
  palette:
    # 亮色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至暗色模式

    # 暗色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式

markdown_extensions:
  - toc:
      permalink: true        # 添加段落链接
      toc_depth: 3          # 目录深度
      separator: "_"        # 标题锚点分隔符
      title: "目录"         # 目录标题

plugins:
  - blog:
      blog_dir: blog
      archive_date_format: MMMM yyyy
      post_url_format: "{slug}"
      post_excerpt: optional

nav: 
    - blog: index.md
    - summary: summary/index.md
      -2025年: summary/25year/index.md  
        - 2025年1月: summary/25year/1.md
    - 笔记: note/index.md
        - 计组:note/csapp.md
        - 计网:note/cs-net.md
        - 数据结构:note/datastructure.md
        - 建站教程:note/site-construction.md
